### ISSUE TITLE
02-DI容器

### ISSUE THREAD

**Issue by LugeJiayi** [mohuishou/go-design-pattern#3]
![impicture_20220322_174729](https://user-images.githubusercontent.com/49866578/159452935-6e384e49-7439-4b20-9cdc-c954c7f7a440.png)
这个error没有处理 会发生panic

**Comment by mohuishou** [comment]
> ![impicture_20220322_174729](https://user-images.githubusercontent.com/49866578/159452935-6e384e49-7439-4b20-9cdc-c954c7f7a440.png) 这个error没有处理 会发生panic

这里返回了吧

**Comment by LugeJiayi** [comment]
> 

这个是我加上的啦 你看看你的代码

**Comment by LugeJiayi** [comment]
不过你整个设计模式讲的好棒！！！
爱了
